# .github/workflows/test.yml
name: Run Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Enable Corepack and pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate   # pick your pnpm version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
